-- MySQL Script generated by MySQL Workbench
-- Thu Oct  9 08:29:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema heavenshoptestdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema heavenshoptestdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heavenshoptestdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `heavenshoptestdb` ;

-- -----------------------------------------------------
-- Table `heavenshoptestdb`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `heavenshoptestdb`.`categories` ;

CREATE TABLE IF NOT EXISTS `heavenshoptestdb`.`categories` (
  `id_category` INT(11) NOT NULL AUTO_INCREMENT,
  `name_category` VARCHAR(100) NOT NULL,
  `description_category` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `heavenshoptestdb`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `heavenshoptestdb`.`products` ;

CREATE TABLE IF NOT EXISTS `heavenshoptestdb`.`products` (
  `id_product` INT(11) NOT NULL AUTO_INCREMENT,
  `name_product` VARCHAR(150) NOT NULL,
  `description_product` TEXT NULL DEFAULT NULL,
  `status_product` ENUM('Active', 'Inactive') NULL DEFAULT 'Active',
  `color_product` VARCHAR(50) NULL DEFAULT NULL,
  `size_product` VARCHAR(50) NULL DEFAULT NULL,
  `stock_product` INT(11) NOT NULL DEFAULT 0,
  `price_product` DECIMAL(10,2) NOT NULL,
  `image_product` VARCHAR(255) NULL DEFAULT NULL,
  `id_category` INT(11) NOT NULL,
  PRIMARY KEY (`id_product`),
  INDEX `fk_products_categories` (`id_category` ASC),
  CONSTRAINT `fk_products_categories`
    FOREIGN KEY (`id_category`)
    REFERENCES `heavenshoptestdb`.`categories` (`id_category`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `heavenshoptestdb`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `heavenshoptestdb`.`roles` ;

CREATE TABLE IF NOT EXISTS `heavenshoptestdb`.`roles` (
  `id_role` INT(11) NOT NULL AUTO_INCREMENT,
  `name_role` VARCHAR(50) NOT NULL,
  `description_role` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id_role`),
  UNIQUE INDEX `name_role` (`name_role` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `heavenshoptestdb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `heavenshoptestdb`.`users` ;

CREATE TABLE IF NOT EXISTS `heavenshoptestdb`.`users` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `name_user` VARCHAR(150) NOT NULL,
  `email_user` VARCHAR(150) NOT NULL,
  `password_user` VARCHAR(255) NOT NULL,
  `status_user` ENUM('active', 'inactive') NULL DEFAULT 'active',
  `id_role` INT(11) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `email_user` (`email_user` ASC),
  INDEX `fk_user_role` (`id_role` ASC),
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`id_role`)
    REFERENCES `heavenshoptestdb`.`roles` (`id_role`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `heavenshoptestdb`.`refreshTokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `heavenshoptestdb`.`refreshT_tokens` ;

CREATE TABLE IF NOT EXISTS `heavenshoptestdb`.`refresh_tokens` (
  `id_token` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `expires_at` DATETIME NOT NULL,
  PRIMARY KEY(`id_token`),
  INDEX `fk_user_refresh_idx` (`id_user` ASC),
  CONSTRAINT `fk_user_refreshToken`
    FOREIGN KEY (`id_user`)
    REFERENCES `heavenshoptestdb`.`users` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
